INSERT INTO cliente (nome) VALUES ('João');
-- INSERT INTO cliente (nome) VALUES ('Maria');
-- INSERT INTO cliente (nome) VALUES ('Pedro');
-- INSERT INTO cliente (nome) VALUES ('Ana');
-- INSERT INTO cliente (nome) VALUES ('Carlos');
-- INSERT INTO cliente (nome) VALUES ('Sandra');
-- INSERT INTO cliente (nome) VALUES ('Lucas');
-- INSERT INTO cliente (nome) VALUES ('Laura');
-- INSERT INTO cliente (nome) VALUES ('Miguel');
-- INSERT INTO cliente (nome) VALUES ('Isabel');
